CREATE TABLE [dbo].[TBGRUPOVEICULO] (
    [ID]        INT          IDENTITY (1, 1) NOT NULL,
    [NOMEGRUPO] VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_TBGRUPOVEICULO] PRIMARY KEY CLUSTERED ([ID] ASC)
);

