
USE [LocadoraAutomoveisDB]
GO

/****** Object:  Table [dbo].[TBGRUPOVEICULO]    Script Date: 27/06/2022 21:09:58 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE TABLE [dbo].[TBGRUPOVEICULO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NOMEGRUPO] [varchar](50) NOT NULL,
 CONSTRAINT [PK_TBGRUPOVEICULO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

--Syntax Error: Incorrect syntax near OPTIMIZE_FOR_SEQUENTIAL_KEY.
--
--CREATE TABLE [dbo].[TBGRUPOVEICULO](
--	[ID] [int] IDENTITY(1,1) NOT NULL,
--	[NOMEGRUPO] [varchar](50) NOT NULL,
-- CONSTRAINT [PK_TBGRUPOVEICULO] PRIMARY KEY CLUSTERED 
--(
--	[ID] ASC
--)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
--) ON [PRIMARY]



GO
