
USE [LocadoraAutomoveisDB]
GO

/****** Object:  Table [dbo].[TBPLANO]    Script Date: 30/06/2022 20:43:14 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE TABLE [dbo].[TBPLANO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[GRUPO_ID] [int] NOT NULL,
	[DESCRICAO] [varchar](150) NOT NULL,
	[VALORDIARIO] [real] NOT NULL,
	[VALORPORKM] [real] NOT NULL,
	[LIMITEQUILOMETRAGEM] [int] NOT NULL,
 CONSTRAINT [PK_TBPLANO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
