
USE [LocadoraAutomoveisDB]
GO

/****** Object:  Table [dbo].[TBVEICULO]    Script Date: 03/07/2022 19:10:16 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE TABLE [dbo].[TBVEICULO](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[MODELO] [varchar](70) NOT NULL,
	[PLACA] [varchar](10) NOT NULL,
	[COR] [varchar](50) NOT NULL,
	[ANO] [varchar](4) NOT NULL,
	[TIPOCOMBUSTIVEL] [varchar](50) NOT NULL,
	[CAPACIDADETANQUE] [real] NOT NULL,
	[STATUSVEICULO] [varchar](50) NOT NULL,
	[QUILOMETRAGEMATUAL] [int] NOT NULL,
	[FOTO] [varbinary](max) NOT NULL,
	[IDGRUPOVEICULO] [int] NOT NULL,
 CONSTRAINT [PK_TBVEICULO] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

--Syntax Error: Incorrect syntax near OPTIMIZE_FOR_SEQUENTIAL_KEY.
--
--CREATE TABLE [dbo].[TBVEICULO](
--	[ID] [int] IDENTITY(1,1) NOT NULL,
--	[MODELO] [varchar](70) NOT NULL,
--	[PLACA] [varchar](10) NOT NULL,
--	[COR] [varchar](50) NOT NULL,
--	[ANO] [varchar](4) NOT NULL,
--	[TIPOCOMBUSTIVEL] [varchar](50) NOT NULL,
--	[CAPACIDADETANQUE] [real] NOT NULL,
--	[STATUSVEICULO] [varchar](50) NOT NULL,
--	[QUILOMETRAGEMATUAL] [int] NOT NULL,
--	[FOTO] [varbinary](max) NOT NULL,
--	[IDGRUPOVEICULO] [int] NOT NULL,
-- CONSTRAINT [PK_TBVEICULO] PRIMARY KEY CLUSTERED 
--(
--	[ID] ASC
--)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
--) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]



GO
