ALTER TABLE [dbo].[TBVEICULO]  WITH CHECK ADD  CONSTRAINT [FK_TBVEICULO_TBGRUPOVEICULO] FOREIGN KEY([IDGRUPOVEICULO])
REFERENCES [dbo].[TBGRUPOVEICULO] ([ID])
GO

ALTER TABLE [dbo].[TBVEICULO] CHECK CONSTRAINT [FK_TBVEICULO_TBGRUPOVEICULO]