ALTER TABLE [dbo].[TBPLANO]  WITH CHECK ADD  CONSTRAINT [FK_TBPLANO_TBGRUPOVEICULO] FOREIGN KEY([GRUPO_ID])
REFERENCES [dbo].[TBGRUPOVEICULO] ([ID])
GO

ALTER TABLE [dbo].[TBPLANO] CHECK CONSTRAINT [FK_TBPLANO_TBGRUPOVEICULO]