USE [LocadoraAutomoveisDb]
GO

/****** Object:  Table [dbo].[TBCONDUTOR]    Script Date: 01/07/2022 11:43:29 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TBCONDUTOR](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nome] [varchar](50) NOT NULL,
	[Cpf] [varchar](20) NOT NULL,
	[Cnh] [varchar](20) NOT NULL,
	[VencimentoCnh] [date] NOT NULL,
	[Email] [varchar](50) NOT NULL,
	[Endereco] [varchar](100) NOT NULL,
	[Telefone] [varchar](20) NOT NULL,
	[Cliente_Id] [int] NOT NULL,
 CONSTRAINT [PK_TBCondutor] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TBCONDUTOR]  WITH CHECK ADD  CONSTRAINT [FK_TBCONDUTOR_TBCLIENTE] FOREIGN KEY([Cliente_Id])
REFERENCES [dbo].[TBCLIENTE] ([id])
GO

ALTER TABLE [dbo].[TBCONDUTOR] CHECK CONSTRAINT [FK_TBCONDUTOR_TBCLIENTE]
GO


