CREATE TABLE [dbo].[TBPLANO] (
    [ID]                             INT  IDENTITY (1, 1) NOT NULL,
    [GRUPO_ID]                       INT  NOT NULL,
    [VALORDIARIO_DIARIO]             REAL NOT NULL,
    [VALORPORKM_DIARIO]              REAL NOT NULL,
    [LIMITEQUILOMETRAGEM_CONTROLADO] INT  NOT NULL,
    [VALORDIARIO_CONTROLADO]         INT  NOT NULL,
    [VALORPORKM_CONTROLADO]          INT  NOT NULL,
    [VALORDIARIO_LIVRE]              INT  NOT NULL,
    CONSTRAINT [PK_TBPLANO] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_TBPLANO_TBGRUPOVEICULO] FOREIGN KEY ([GRUPO_ID]) REFERENCES [dbo].[TBGRUPOVEICULO] ([ID])
);

