CREATE TABLE [dbo].[TBTAXA] (
    [ID]        UNIQUEIDENTIFIER NULL,
    [DESCRICAO] VARCHAR (150)    NOT NULL,
    [TIPO]      VARCHAR (50)     NOT NULL,
    [VALOR]     REAL             NOT NULL
);

