CREATE TABLE [dbo].[TBTAXA] (
    [ID]        INT           IDENTITY (1, 1) NOT NULL,
    [DESCRICAO] VARCHAR (150) NOT NULL,
    [TIPO]      VARCHAR (50)  NOT NULL,
    [VALOR]     REAL          NOT NULL,
    CONSTRAINT [PK_TBTAXA] PRIMARY KEY CLUSTERED ([ID] ASC)
);

